# Generated by Django 5.2.8 on 2025-12-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=255)),
                ('_login', models.CharField(max_length=255)),
                ('_password', models.CharField(max_length=255)),
                ('_role', models.CharField(choices=[('MANAGER', 1), ('WAITER', 2), ('COOK', 3)], max_length=50)),
            ],
        ),
    ]
