# Generated by Django 5.2.8 on 2025-12-07 23:52

import POS_app.business.Items.Utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('_login', models.CharField(max_length=255, unique=True, verbose_name='Login')),
                ('_password', models.CharField(max_length=255, verbose_name='Password')),
                ('_role', models.CharField(choices=[('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('COOK', 'Cook')], max_length=50, verbose_name='Employee Role')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Menu Item ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('currency', models.CharField(choices=[('ZLOTY', 'PLN'), ('EURO', 'EUR'), ('KORUNA', 'CZK')], default='ZLOTY', max_length=20, verbose_name='Currency')),
                ('prep_time_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimal preparation time in minutes')),
                ('active', models.BooleanField(default=True, verbose_name='Active status')),
                ('course', models.CharField(default='', max_length=255, verbose_name='Course')),
                ('tax', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('oi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order Item ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('AWAITING_PREPARATION', 'Awaiting preparation'), ('IN_PREPARATION', 'In preparation'), ('READY', 'Ready'), ('PAID', 'Paid'), ('ARCHIVED', 'Archived'), ('CANCELED', 'Canceled')], default=POS_app.business.Items.Utils.OrderStatus['NEW'], max_length=50, verbose_name='Status')),
                ('ready_at', models.DateTimeField(verbose_name='Ready at')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POS_app.menuitems', verbose_name='FK Menu Item ID')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('displayed_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Displayed ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ready_at', models.DateTimeField(verbose_name='Ready at')),
                ('delivered_at', models.DateTimeField(verbose_name='Paid at')),
                ('paid_at', models.DateTimeField(verbose_name='Paid at')),
                ('archived_at', models.DateTimeField(verbose_name='Archived at')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('AWAITING_PREPARATION', 'Awaiting preparation'), ('IN_PREPARATION', 'In preparation'), ('READY', 'Ready'), ('PAID', 'Paid'), ('ARCHIVED', 'Archived'), ('CANCELED', 'Canceled')], default=POS_app.business.Items.Utils.OrderStatus['NEW'], max_length=50, verbose_name='Status')),
                ('is_takeaway', models.BooleanField(verbose_name='Is takeaway')),
                ('scheduled_pick_up', models.DateTimeField(verbose_name='Scheduled pick up')),
                ('estimated_pick_up', models.DateTimeField(verbose_name='Estimated pick up')),
                ('table_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Table number')),
                ('notes', models.CharField(default='', max_length=255, verbose_name='Notes')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS_app.employees', verbose_name='Assigned Waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Price')),
                ('currency', models.CharField(choices=[('ZLOTY', 'PLN'), ('EURO', 'EUR'), ('KORUNA', 'CZK')], default='ZLOTY', max_length=20, verbose_name='Currency')),
                ('paid_at', models.DateTimeField(verbose_name='Paid at')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POS_app.orders', verbose_name='FK Order ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServingRules',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Serving Rules ID')),
                ('position', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position')),
                ('course', models.CharField(default='', max_length=255, verbose_name='Course')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='POS_app.orders', verbose_name='FK Order ID')),
                ('oi_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='POS_app.orderitems', verbose_name='FK Order Item ID')),
            ],
        ),
    ]
