# Generated by Django 5.2.8 on 2025-12-08 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='ready_at',
            field=models.DateTimeField(blank=True, verbose_name='Ready at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='archived_at',
            field=models.DateTimeField(blank=True, verbose_name='Archived at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='estimated_pick_up',
            field=models.DateTimeField(blank=True, verbose_name='Estimated pick up'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paid_at',
            field=models.DateTimeField(blank=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_at',
            field=models.DateTimeField(blank=True, verbose_name='Ready at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='scheduled_pick_up',
            field=models.DateTimeField(blank=True, verbose_name='Scheduled pick up'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='table_no',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Table number'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_at',
            field=models.DateTimeField(blank=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='servingrules',
            name='position',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position'),
        ),
    ]
