# Generated by Django 5.2.8 on 2025-12-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('COOK', 'Cook')], max_length=50),
        ),
    ]
