# Generated by Django 5.2.8 on 2025-12-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0002_alter_orderitems_quantity_alter_orderitems_ready_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ready at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='estimated_pick_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated pick up'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ready at'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='scheduled_pick_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled pick up'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
    ]
