# Generated by Django 5.2.8 on 2025-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0002_alter_employees__role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.AddField(
            model_name='employees',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='_login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='_name',
            field=models.CharField(max_length=255, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='_password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('WAITER', 'Waiter'), ('COOK', 'Cook')], max_length=50, verbose_name='Employee Role'),
        ),
    ]
