# Generated by Django 5.2.8 on 2025-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0003_alter_orderitems_ready_at_alter_orders_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
