# Generated by Django 5.2.8 on 2025-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0004_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
