# Generated by Django 5.2.8 on 2025-12-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0005_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='_login',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Login'),
        ),
    ]
