# Generated by Django 5.2.8 on 2025-12-09 20:24

import POS_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0006_alter_employees__login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='_password',
            field=models.CharField(max_length=255, validators=[POS_app.models.password_validator], verbose_name='Password'),
        ),
    ]
