# Generated by Django 5.2.8 on 2025-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_app', '0007_alter_employees__password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
